spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hermez_db
    username: root
    password: R00T
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    database: mysql
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    open-in-view: true
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs